import Link from "next/link";
import { ClientResults } from "./ClientResults";
import { HeroVisual } from "./HeroVisual";
import { SiteFooter } from "./SiteFooter";
import { SiteHeader } from "./SiteHeader";
import { FOUNDER_NAME, LEGAL_NAME, SERVICE_PRICES, SITE_URL, withTrailingSlash } from "../site";

type Locale = "ru" | "en";

const copy = {
  ru: {
    hero: ["Виза начинается за год до подачи", "Сравним маршруты и покажем, что уже можно доказать", "Для специалистов, основателей и семей, которые рассматривают Великобританию, США, Испанию или Францию. Сначала проверяем цель, статус и доказательства, затем предлагаем реалистичный план подготовки.", "Проверить профиль за 2–3 минуты", "Сравнить маршруты", "Короткий этап — 2–3 минуты · содержательный ответ в течение одного рабочего дня", "Совокупный опыт с 2021 года: 10 000+ разобранных профилей · направления в 14 странах"],
    audiences: {
      eyebrow: "Кому помогаем", title: "Начинаем не со страны, а с Вашей ситуации", intro: "Один и тот же опыт может поддерживать несколько программ. Мы сопоставляем цель, нужный статус, сроки и факты, которые можно подтвердить.",
      items: [
        ["01", "Специалисты и руководители", "Отделяем личный вклад в продукты, команды и бизнес-результаты от обычных должностных обязанностей."],
        ["02", "Основатели и предприниматели", "Сравниваем маршруты через достижения, стартап или инвестиции и проверяем роль основателя в результатах бизнеса."],
        ["03", "Исследователи и авторы", "Собираем академическое, профессиональное и независимое признание в одну проверяемую траекторию."],
        ["04", "Удаленные специалисты и семьи", "Проверяем формат занятости, договоры, доход, семейный комплект и последствия выбранного статуса."],
      ],
    },
    problem: {
      eyebrow: "Почему одного сильного опыта недостаточно", title: "Заявка теряет убедительность в разрывах между фактами", body: "Сильная карьера не превращается в доказательства автоматически. Роль может потеряться внутри командного результата, цифры — разойтись между документами, а публикации — не подтвердить личный вклад. Исправлять структуру после отказа обычно дольше и дороже, чем проверить ее до подачи.",
      items: [["Личный вклад", "Показываем, что именно сделал заявитель и как его решения связаны с результатом."], ["Независимый контекст", "Отделяем внутреннее подтверждение компании от признания за ее пределами."], ["Согласованность", "Сверяем даты, роли, показатели и единицы измерения во всем комплекте."]],
    },
    development: {
      eyebrow: "Профиль можно подготовить", title: "Отсутствие публикаций на старте не закрывает маршрут", body: "Мы не ограничиваемся оценкой уже готового профиля. Если доказательств недостаточно, строим план на 3–12 месяцев: выбираем реальные проекты и профессиональные действия, заранее определяем измеримый результат и источники, которые смогут его подтвердить.", note: "Цель — не создать видимость публичности, а довести фактический опыт до состояния, в котором его можно последовательно и честно доказать.", link: "Как устроено развитие профиля",
      items: [["01", "Находим основу", "Разбираем проекты, решения, рост ответственности и результаты, которые уже есть в карьере или бизнесе."], ["02", "Строим план пробелов", "Определяем, чего не хватает: независимой оценки, публичного следа, рекомендателей, метрик или нового результата."], ["03", "Создаем подтверждаемые результаты", "Планируем выступления, авторские материалы, экспертные роли и проекты, которые продолжают профессиональную траекторию."], ["04", "Собираем доказательства", "Фиксируем итог, личный вклад, масштаб и независимый источник до того, как детали потеряются."]],
    },
    compare: {
      eyebrow: "Сравнение", title: "У стран разные критерии, программы и итоговый статус", intro: "Мы не выбираем маршрут по названию профессии. Сравнение начинается с результата, который нужен человеку, а затем переходит к ограничениям и доказательствам.", headers: ["Направление", "Основная задача", "Что проверяем", "Подготовка"], link: "Открыть полное сравнение",
      rows: [["UK · Global Talent", "Карьера без привязки к работодателю", "Признание, личный вклад, независимые источники", "от 2 месяцев"], ["UK · Innovator Founder", "Запуск инновационного стартапа", "Инновационность, жизнеспособность, масштабируемость", "от 2 месяцев"], ["US · EB-1A / NIW", "Иммиграционный маршрут", "Признание либо proposed endeavor", "от 1 месяца"], ["US · O-1 / E-2", "Работа либо инвестиционный бизнес", "Достижения и петиционер либо инвестиции", "от 1 месяца"], ["ES · Digital Nomad", "ВНЖ для удаленной работы", "Занятость, договоры, доход, страхование", "от 1 месяца"], ["FR · Talent", "Проект, стартап или бизнес", "Подкатегория, финансирование и роль", "от 2 месяцев"]],
    },
    services: {
      eyebrow: "Форматы работы", title: "От первого сравнения до подачи и следующих статусов", intro: "Проект можно начать с отдельной задачи или пройти весь цикл одной командой. Состав и границы работы фиксируем до начала платного этапа.", link: "Посмотреть форматы подробно",
      items: [["01", "Предварительная оценка", "Подходящие направления, текущая готовность и вопросы, которые нужно проверить глубже.", "Бесплатно · один рабочий день"], ["02", "Сравнение маршрутов", "Матрица вариантов с итоговым статусом, сроками, ограничениями и доказательственными задачами.", "Отдельный стратегический результат"], ["03", "Аудит доказательной базы", "Карта критериев, реестр сильных фактов, слабые места и план подготовки материалов.", "Для выбранного маршрута"], ["04", "Развитие профиля", "План профессиональных действий на 3–12 месяцев и система фиксации новых результатов.", "Когда профиль еще не готов"], ["05", "Полное сопровождение", "Стратегия, доказательства, рекомендации, формы, партнеры и подача.", "UK от €5 000 · US от €8 000"], ["06", "Продление и семья", "Следующий статус, семейная подача, продление и связанные документы.", "После основного решения"]],
    },
    process: { eyebrow: "Как работаем", title: "Четыре результата вместо длинной цепочки действий", items: [["01", "Карта маршрутов", "Сравниваем статус, срок, ограничения и положение семьи."], ["02", "Матрица доказательств", "Связываем каждый центральный тезис с фактом, источником и критерием."], ["03", "План подготовки", "Фиксируем пробелы, задачи, ответственных и контрольные даты."], ["04", "Согласованный комплект", "Проверяем факты между документами и ведем подачу в согласованном объеме."]]},
    articles: { eyebrow: "Что изменилось", title: "Следим за правилами и отделяем действующие нормы от проектов", all: "Все материалы", read: "Разобрать изменение", items: [["США · 27 августа 2026", "Приостановка выдачи иммиграционных виз гражданам России", "Что это меняет для консульского этапа EB-1A и NIW — и чего не меняет.", "/blog/us-immigrant-visa-issuance-pause-russia/"], ["Великобритания · 6 марта 2026", "HC 1691: почему правила зависят от даты подачи", "Календарь вступления в силу ключевых положений.", "/blog/uk-hc-1691-dates/"], ["Испания · 20 февраля 2026", "Порог дохода DNV в 2026 году и расчет для семьи", "Расчет 200%, 75% и 25% после повышения испанского SMI.", "/blog/spain-dnv-income-2026/"]]},
    pricing: ["Стоимость и сроки", "Финальный бюджет зависит от маршрута и состояния профиля", "После предварительной оценки определяем, нужна ли отдельная стратегия, развитие профиля или полное сопровождение. До платного этапа письменно фиксируем состав работы, срок и стоимость.", "Цены указаны за работу Samotsvet. Государственные сборы, переводы, лицензированные партнеры и другие внешние расходы рассчитываются отдельно, если прямо не включены в предложение."],
    faq: { eyebrow: "Частые вопросы", title: "Что важно понять до начала проекта", items: [["Можно ли обратиться без публикаций и выступлений?", "Да. Мы сначала проверяем фактический опыт и доступные маршруты. Если независимых доказательств пока недостаточно, предлагаем план развития профиля. Вывод зависит от программы, срока и исходных фактов."], ["Предварительная оценка показывает процент одобрения?", "Нет. Мы не выдаем псевдоточный процент. Результат показывает подходящие направления, готовность профиля и вопросы, которые требуют документальной проверки."], ["Вы работаете только с готовыми кейсами?", "Нет. Можно начать за 3–12 месяцев до подачи и последовательно подготовить проекты, доказательства, рекомендателей и публичный след."], ["Кто отвечает за юридические вопросы конкретной страны?", "Samotsvet ведет стратегию и подготовку проекта. Когда вопрос требует лицензированного специалиста соответствующей юрисдикции, мы подключаем профильного партнера и заранее объясняем его роль."], ["Можно ли сравнить несколько стран?", "Да. Сопоставляем итоговый статус, срок, зависимость от работодателя или бизнеса, положение семьи и реальные доказательства в Вашей ситуации."]]},
    closing: ["Первый шаг", "Получите карту направлений и готовности профиля", "Короткий этап занимает 2–3 минуты. После него можно сразу дополнить профиль, а команда получит данные для содержательного ответа в течение одного рабочего дня.", "Получить быструю проверку"],
  },
  en: {
    hero: ["The visa process starts a year before the application", "Compare routes and see what you can already evidence", "For specialists, founders and families considering the United Kingdom, United States, Spain or France. We first examine the objective, status and evidence, then propose a realistic preparation plan.", "Check your profile in 2–3 minutes", "Compare routes", "Short stage: 2–3 minutes · substantive reply within one business day", "Combined experience since 2021: 10,000+ profiles reviewed · route work across 14 countries"],
    audiences: { eyebrow: "Who we help", title: "We start with your circumstances, not a country", intro: "The same experience may support several programmes. We compare the objective, required status, timing and facts that can be evidenced.", items: [["01", "Specialists and senior leaders", "We distinguish personal contribution to products, teams and commercial outcomes from ordinary responsibilities."], ["02", "Founders and entrepreneurs", "We compare achievement, start-up and investment routes and connect the founder's role to business outcomes."], ["03", "Researchers and authors", "We bring academic, professional and independent recognition into one verifiable trajectory."], ["04", "Remote professionals and families", "We review working arrangements, contracts, income, family documents and the effects of the selected status."]]},
    problem: { eyebrow: "Why strong experience is not enough on its own", title: "A case loses credibility in the gaps between facts", body: "A strong career does not turn into evidence automatically. Personal contribution may disappear inside a team result, figures may conflict across documents and a publication may not establish the applicant's role. Correcting the structure after a refusal is usually slower and more expensive than testing it before filing.", items: [["Personal contribution", "We show what the applicant did and how their decisions connect to the outcome."], ["Independent context", "We separate internal company evidence from recognition outside it."], ["Consistency", "We reconcile dates, roles, metrics and units across the full record."]]},
    development: { eyebrow: "A profile can be developed", title: "No publications at the outset does not necessarily close the route", body: "We do more than assess an already finished profile. If evidence is insufficient, we build a 3–12 month plan: select genuine projects and professional activity, define measurable outcomes and record the sources that can verify them.", note: "The aim is not to manufacture visibility. It is to bring real experience to a point at which it can be presented consistently and honestly.", link: "How profile development works", items: [["01", "Find the foundation", "Review projects, decisions, increasing responsibility and outcomes already present in the career or business."], ["02", "Map the gaps", "Identify missing independent assessment, public record, referees, metrics or new results."], ["03", "Create verifiable outcomes", "Plan speaking, authorship, expert roles and projects that genuinely continue the professional trajectory."], ["04", "Capture the evidence", "Record the outcome, personal contribution, scale and independent source before detail is lost."]]},
    compare: { eyebrow: "Comparison", title: "Each country has different criteria, programmes and outcomes", intro: "We do not select a route from a job title. The comparison starts with the outcome required, then turns to restrictions and evidence.", headers: ["Route", "Primary objective", "What we examine", "Preparation"], link: "Open the full comparison", rows: [["UK · Global Talent", "Career without employer sponsorship", "Recognition, contribution, independent sources", "from 2 months"], ["UK · Innovator Founder", "Build an innovative start-up", "Innovation, viability and scalability", "from 2 months"], ["US · EB-1A / NIW", "An immigrant route", "Recognition or the proposed endeavour", "from 1 month"], ["US · O-1 / E-2", "Work or an investment business", "Achievements and petitioner, or investment", "from 1 month"], ["ES · Digital Nomad", "Residence for remote work", "Work, contracts, income and insurance", "from 1 month"], ["FR · Talent", "A project, start-up or business", "Subcategory, funding and role", "from 2 months"]]},
    services: { eyebrow: "Ways to work with us", title: "From the first comparison to filing and later status stages", intro: "A project may begin with one defined task or continue through the full cycle with one team. Scope and boundaries are agreed before paid work begins.", link: "View all working formats", items: [["01", "Preliminary assessment", "Potential routes, present readiness and questions requiring deeper review.", "Free · one business day"], ["02", "Route comparison", "A matrix of outcomes, timing, restrictions and evidential tasks.", "A standalone strategic deliverable"], ["03", "Evidence audit", "A criteria map, register of strong facts, weaknesses and preparation plan.", "For a selected route"], ["04", "Profile development", "A 3–12 month plan and a system for recording new outcomes.", "Where the profile is not yet ready"], ["05", "Full support", "Strategy, evidence, references, forms, partners and filing.", "UK from €5,000 · US from €8,000"], ["06", "Extensions and family", "The next status, family filing, extension and related documents.", "Following the main decision"]]},
    process: { eyebrow: "How we work", title: "Four deliverables rather than a long list of actions", items: [["01", "Route map", "We compare status, timing, restrictions and the position of the family."], ["02", "Evidence matrix", "Each central proposition is connected to a fact, source and criterion."], ["03", "Preparation plan", "We record gaps, tasks, owners and review dates."], ["04", "Reconciled bundle", "We check facts across documents and manage the agreed filing scope."]]},
    articles: { eyebrow: "What changed", title: "We track the rules and distinguish current law from proposals", all: "All articles", read: "Review the change", items: [["United States · 27 August 2026", "Immigrant-visa issuance pause for Russian nationals", "What it changes for the EB-1A and NIW consular stage — and what it does not.", "/en/blog/us-immigrant-visa-issuance-pause-russia/"], ["United Kingdom · 6 March 2026", "HC 1691: why the filing date determines which rules apply", "A timetable for the key changes.", "/en/blog/uk-hc-1691-dates/"], ["Spain · 20 February 2026", "The 2026 DNV income threshold and family calculation", "The 200%, 75% and 25% calculation following the SMI increase.", "/en/blog/spain-dnv-income-2026/"]]},
    pricing: ["Fees and timing", "The final budget depends on the route and present readiness", "Following the preliminary assessment, we establish whether the matter needs a standalone strategy, profile development or full support. Scope, timing and fee are agreed in writing before paid work begins.", "Fees cover Samotsvet's work. Government fees, translations, licensed partners and other external costs are quoted separately unless expressly included."],
    faq: { eyebrow: "Common questions", title: "What to understand before a project begins", items: [["Can I approach you without publications or speaking experience?", "Yes. We first review the real experience and available routes. If independent evidence is insufficient, we propose a profile-development plan. The conclusion depends on the programme, timing and starting facts."], ["Does the preliminary assessment provide an approval percentage?", "No. We do not produce a spurious percentage. The result identifies potential routes, present readiness and questions requiring documentary review."], ["Do you only work with filing-ready cases?", "No. A project can start 3–12 months before filing so that projects, evidence, referees and the public record are developed in sequence."], ["Who handles jurisdiction-specific legal questions?", "Samotsvet leads strategy and project preparation. Where a matter requires a licensed professional in the relevant jurisdiction, we involve a specialist partner and explain their role in advance."], ["Can you compare several countries?", "Yes. We compare the eventual status, timing, dependence on employment or business, family position and evidence available in your circumstances."]]},
    closing: ["First step", "Receive a map of potential routes and profile readiness", "The short stage takes 2–3 minutes. You can then add the full profile while the team receives enough information for a substantive reply within one business day.", "Run the quick check"],
  },
} as const;

export function HomePage({ locale = "ru" }: { locale?: Locale }) {
  const text = copy[locale];
  const isEnglish = locale === "en";
  const base = isEnglish ? "/en" : "";
  const assessmentPath = withTrailingSlash(`${base}/assessment`);
  const comparePath = withTrailingSlash(`${base}/compare`);
  const servicesPath = withTrailingSlash(`${base}/services`);
  const faqData = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: text.faq.items.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  const serviceData = { "@context": "https://schema.org", "@type": "ProfessionalService", "@id": `${SITE_URL}/#professional-service`, name: "Samotsvet", legalName: LEGAL_NAME, url: `${SITE_URL}${base || "/"}`, logo: `${SITE_URL}/samotsvet-logo.svg`, founder: { "@type": "Person", name: FOUNDER_NAME }, areaServed: ["United Kingdom", "Spain", "United States", "France"] };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceData) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqData) }} />
    <SiteHeader locale={locale} />
    <main>
      <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow">{text.hero[0]}</p><h1>{text.hero[1]}</h1><p className="hero-lede">{text.hero[2]}</p><div className="hero-actions"><Link className="button button-primary" href={assessmentPath}>{text.hero[3]}</Link><Link className="button button-secondary" href={comparePath}>{text.hero[4]}</Link></div><p className="hero-response">{text.hero[5]}</p><p className="hero-note">{text.hero[6]}</p></div><HeroVisual locale={locale} /></section>

      <section className="section-shell section-block audience-section"><Heading eyebrow={text.audiences.eyebrow} title={text.audiences.title} intro={text.audiences.intro} /><div className="audience-grid">{text.audiences.items.map(([n,t,b]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>

      <section className="problem-band"><div className="section-shell problem-layout"><div><p className="eyebrow eyebrow-light">{text.problem.eyebrow}</p><h2>{text.problem.title}</h2><p>{text.problem.body}</p></div><div className="problem-list">{text.problem.items.map(([t,b]) => <article key={t}><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>

      <section className="section-shell section-block development-evidence"><Heading eyebrow={text.development.eyebrow} title={text.development.title} intro={text.development.body} /><p className="development-note">{text.development.note}</p><div className="development-steps">{text.development.items.map(([n,t,b]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div><Link className="text-link" href={withTrailingSlash(`${base}/profile-development`)}>{text.development.link} <span aria-hidden="true">↗</span></Link></section>

      <section className="comparison-preview" id="directions"><div className="section-shell section-block"><Heading eyebrow={text.compare.eyebrow} title={text.compare.title} intro={text.compare.intro} /><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr>{text.compare.headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{text.compare.rows.map(row => <tr key={row[0]}>{row.map(cell => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><Link className="button button-secondary comparison-link" href={comparePath}>{text.compare.link}</Link></div></section>

      <section className="section-shell section-block services-section" id="services"><Heading eyebrow={text.services.eyebrow} title={text.services.title} intro={text.services.intro} /><div className="service-card-grid">{text.services.items.map(([n,t,b,m]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p><strong>{m}</strong></article>)}</div><Link className="text-link" href={servicesPath}>{text.services.link} <span aria-hidden="true">↗</span></Link></section>

      <ClientResults locale={locale} />

      <section className="section-shell section-block compact-process" id="process"><Heading eyebrow={text.process.eyebrow} title={text.process.title} /><ol>{text.process.items.map(([n,t,b]) => <li key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></li>)}</ol></section>

      <section className="editorial-section"><div className="section-shell section-block"><div className="section-heading"><div><p className="eyebrow">{text.articles.eyebrow}</p><h2>{text.articles.title}</h2></div><Link className="text-link" href={withTrailingSlash(`${base}/blog`)}>{text.articles.all} <span aria-hidden="true">↗</span></Link></div><div className="article-grid">{text.articles.items.map(([tag,title,body,href]) => <article className="article-card" key={href}><p className="article-tag">{tag}</p><h3>{title}</h3><p>{body}</p><Link href={href}>{text.articles.read} <span aria-hidden="true">→</span></Link></article>)}</div></div></section>

      <section className="section-shell pricing-strip" id="pricing"><div><p className="eyebrow">{text.pricing[0]}</p><h2>{text.pricing[1]}</h2></div><div><p>{text.pricing[2]}</p><small className="pricing-note">{text.pricing[3]}</small></div><div className="price-grid">{SERVICE_PRICES.map(item => <div className="price-item" key={item.code}><span>{isEnglish ? item.countryEn : item.countryRu}</span><strong>{isEnglish ? item.priceEn : item.price}</strong><small>{isEnglish ? "Preparation" : "Подготовка"}: {isEnglish ? item.timelineEn : item.timelineRu}</small>{isEnglish && "noteEn" in item ? <small>{item.noteEn}</small> : !isEnglish && "noteRu" in item ? <small>{item.noteRu}</small> : null}</div>)}</div></section>

      <section className="section-shell section-block faq-section"><Heading eyebrow={text.faq.eyebrow} title={text.faq.title} /><div className="faq-list">{text.faq.items.map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>

      <section className="section-shell closing-cta"><div><p className="eyebrow eyebrow-light">{text.closing[0]}</p><h2>{text.closing[1]}</h2></div><div><p>{text.closing[2]}</p><Link className="button button-gold" href={assessmentPath}>{text.closing[3]}</Link></div></section>
    </main>
    <SiteFooter locale={locale} />
  </>;
}

function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className={`section-heading${intro ? "" : " compact-heading"}`}><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{intro ? <p>{intro}</p> : null}</div>;
}
