import Link from "next/link";
import Image from "next/image";
import { ClientResults } from "./ClientResults";
import { PressMentions } from "./PressMentions";
import { SiteFooter } from "./SiteFooter";
import { SiteHeader } from "./SiteHeader";
import { FOUNDER_NAME, LEGAL_NAME, SERVICE_PRICES, SITE_URL, withTrailingSlash } from "../site";

type Locale = "ru" | "en";

const copy = {
  ru: {
    hero: ["С экспертизой Никиты Самоцветова", "Ваш переезд — наш проект", "Вы занимаетесь работой, бизнесом и семьёй. Я сравниваю маршруты и оцениваю основу кейса; команда берёт на себя усиление профиля, доказательства, документы, партнёров и подачу.", "Разобрать мой кейс", "Сравнить маршруты", "Аудит занимает 4–6 минут · результат появится на экране · ответим в течение одного рабочего дня", "10 000+ профилей с 2021 года · 800+ кейсов · 200+ по Великобритании"],
    founder: ["Никита Самоцветов", "Основатель Samotsvet", "LLM International Law and Global Governance", "University of Leeds · 2023"],
    delegation: {
      eyebrow: "Переезд можно передать", title: "Что остаётся на Вас", body: "Один подробный разговор об опыте — обычно полтора-два часа. Подписи там, где они действительно нужны, и решения в ключевых точках проекта.", note: "Разобраться в критериях, подготовить рекомендации, сверить даты и факты между документами, следить за правилами и координировать партнёров — наша работа. О ходе проекта Вы узнаёте из коротких отчётов.", items: ["Разговор об опыте", "Подписи", "Решения в ключевых точках"],
    },
    audiences: {
      eyebrow: "Кому помогаем", title: "Начинаем не со страны, а с Вашей ситуации", intro: "Один и тот же опыт может поддерживать несколько программ. Я сопоставляю цель, нужный статус, сроки и факты, которые можно подтвердить, а команда превращает вывод в план работы.",
      items: [
        ["01", "Специалисты и руководители", "Отделяем личный вклад в продукты, команды и бизнес-результаты от обычных должностных обязанностей."],
        ["02", "Основатели и предприниматели", "Сравниваем маршруты через достижения, стартап или инвестиции и проверяем роль основателя в результатах бизнеса."],
        ["03", "Исследователи и авторы", "Собираем академическое, профессиональное и независимое признание в одну проверяемую траекторию."],
        ["04", "Удаленные специалисты и семьи", "Проверяем формат занятости, договоры, доход, семейный комплект и последствия выбранного статуса."],
      ],
    },
    problem: {
      eyebrow: "Почему одного сильного опыта недостаточно", title: "Заявка теряет убедительность в разрывах между фактами", body: "Сильная карьера не превращается в доказательства автоматически. При оценке я ищу места, где личная роль теряется внутри командного результата, цифры расходятся между документами, а внешнее упоминание не подтверждает вклад. Команда устраняет эти разрывы до подачи.",
      items: [["Личный вклад", "Показываем, что именно сделал заявитель и как его решения связаны с результатом."], ["Независимый контекст", "Отделяем внутреннее подтверждение компании от признания за ее пределами."], ["Согласованность", "Сверяем даты, роли, показатели и единицы измерения во всем комплекте."]],
    },
    development: {
      eyebrow: "Профиль можно подготовить", title: "Отсутствие публикаций на старте не закрывает маршрут", body: "Я не ограничиваюсь оценкой уже готового профиля. Если доказательств недостаточно, мы строим план на 3–12 месяцев: выбираем реальные проекты и профессиональные действия, заранее определяем измеримый результат и источники, которые смогут его подтвердить.", note: "Цель — не создать видимость публичности, а довести фактический опыт до состояния, в котором его можно последовательно и честно доказать.", link: "Как устроено развитие профиля",
      items: [["01", "Находим основу", "Разбираем проекты, решения, рост ответственности и результаты, которые уже есть в карьере или бизнесе."], ["02", "Строим план пробелов", "Определяем, чего не хватает: независимой оценки, публичного следа, рекомендателей, метрик или нового результата."], ["03", "Создаем подтверждаемые результаты", "Планируем выступления, авторские материалы, экспертные роли и проекты, которые продолжают профессиональную траекторию."], ["04", "Собираем доказательства", "Фиксируем итог, личный вклад, масштаб и независимый источник до того, как детали потеряются."]],
    },
    compare: {
      eyebrow: "Гибкость маршрута", title: "Мы не продаём страну", intro: "Я начинаю с цели, сроков, зависимости от работодателя и положения семьи. Затем сопоставляю один и тот же опыт с критериями нескольких программ — предпочтительная страна сама по себе не определяет вывод.", link: "Открыть полное сравнение",
      rows: [["UK", "Global Talent", "Карьера без привязки к одному работодателю", "Признание, личный вклад и независимые подтверждения"], ["UK", "Innovator Founder", "Запуск инновационного стартапа", "Новая идея, жизнеспособность и масштабирование"], ["US", "EB-1A", "Постоянный статус через выдающиеся способности", "Устойчивое признание и достижения высокого уровня"], ["US", "EB-2 NIW", "Постоянный статус через проект в интересах США", "Будущий план и способность его реализовать"], ["US", "O-1", "Временная работа по профессиональному профилю", "Достижения и американский заявитель"], ["US", "E-2", "Управление инвестиционным бизнесом", "Инвестиции, работающий бизнес и контроль"], ["ES", "Digital Nomad", "ВНЖ для удалённой работы", "Занятость, договоры, доход и страхование"], ["FR", "Talent — инновационный проект", "Работа над признанным инновационным проектом", "Проект, принимающая компания и достаточные средства"], ["FR", "Talent — создание бизнеса", "Создание коммерческого проекта во Франции", "Реальный бизнес-план, ресурсы и роль основателя"]],
    },
    services: {
      eyebrow: "Форматы работы", title: "От первого сравнения до подачи и следующих статусов", intro: "Проект можно начать с отдельной задачи или пройти весь цикл одной командой. Состав и границы работы фиксируем до начала платного этапа.", link: "Посмотреть форматы подробно",
      items: [["01", "Аудит профиля", "Несколько потенциальных программ, текущая основа и вопросы, которые нужно проверить глубже.", "Бесплатно · один рабочий день"], ["02", "Сравнение маршрутов", "Матрица вариантов с итоговым статусом, сроками, ограничениями и доказательственными задачами.", "Отдельный стратегический результат"], ["03", "Аудит доказательной базы", "Карта критериев, реестр сильных фактов, слабые места и план подготовки материалов.", "Для выбранного маршрута"], ["04", "Развитие профиля", "План профессиональных действий на 3–12 месяцев и система фиксации новых результатов.", "Когда профиль ещё не готов"], ["05", "Полное сопровождение", "Стратегия, доказательства, рекомендации, формы, партнёры и подача.", "UK от €5 000 · US от €8 000"], ["06", "Продление и семья", "Следующий статус, семейная подача, продление и связанные документы.", "После основного решения"]],
    },
    process: { eyebrow: "Как работаем", title: "Четыре результата вместо длинной цепочки действий", items: [["01", "Карта маршрутов", "Сравниваем статус, срок, ограничения и положение семьи."], ["02", "Матрица доказательств", "Связываем каждый центральный тезис с фактом, источником и критерием."], ["03", "План подготовки", "Фиксируем пробелы, задачи, ответственных и контрольные даты."], ["04", "Согласованный комплект", "Проверяем факты между документами и ведем подачу в согласованном объеме."]]},
    articles: { eyebrow: "Что изменилось", title: "Следим за правилами и отделяем решение суда от его исполнения", all: "Все материалы", read: "Разобрать изменение", items: [["США · 27 августа 2026", "Суд отменил приостановку иммиграционных виз: что известно", "Почему это не решение Верховного суда и что ещё нужно проверять перед консульским этапом EB-1A и NIW.", "/blog/us-immigrant-visa-issuance-pause-russia/"], ["Великобритания · 6 марта 2026", "HC 1691: почему правила зависят от даты подачи", "Календарь вступления в силу ключевых положений.", "/blog/uk-hc-1691-dates/"], ["Испания · 20 февраля 2026", "Порог дохода DNV в 2026 году и расчёт для семьи", "Расчёт 200%, 75% и 25% после повышения испанского SMI.", "/blog/spain-dnv-income-2026/"]]},
    pricing: ["Стоимость и сроки", "Финальный бюджет зависит от маршрута и состояния профиля", "После аудита профиля определяем, нужна ли отдельная стратегия, развитие профиля или полное сопровождение. До платного этапа письменно фиксируем состав работы, срок и стоимость.", "Цены указаны за работу Samotsvet. Государственные сборы, переводы, лицензированные партнёры и другие внешние расходы рассчитываются отдельно, если прямо не включены в предложение."],
    guarantee: {
      eyebrow: "Гарантия работы, а не решения ведомства", title: "Одобрение не гарантирует никто. Мы гарантируем качество своей работы", body: "До старта Вы получаете обоснованную оценку кейса по документам и официальным критериям. Стратегию дополнительно проверяет независимый профильный специалист. Состав проекта, цена и график платежей фиксируются заранее и не меняются по ходу без согласованного изменения объёма.", request: "Запрос ведомства отрабатываем без дополнительной оплаты. При отказе повторную подачу готовим без оплаты нашей работы; государственные сборы, переводы и другие внешние расходы оплачиваются отдельно.", stages: [["40%", "При старте", "Стратегия и подготовка"], ["30%", "После подачи", "Возвращаем при отказе"], ["30%", "После одобрения", "При отказе не начисляется"]], refusal: "Если ведомство отказывает, возвращаем второй платёж — 30% стоимости. Финальные 30% не выставляются. В итоге оплаченной остаётся стартовая часть 40%, которая покрывает уже выполненную стратегию и подготовку.", condition: "Гарантия действует при предоставлении достоверных данных, соблюдении согласованной стратегии и выполнении обязанностей клиента. Точные условия и срок возврата фиксируются в договоре до первого платежа.", link: "Полные условия работы" },
    faq: { eyebrow: "Частые вопросы", title: "Что важно понять до начала проекта", items: [["Можно ли обратиться без публикаций и выступлений?", "Да. Публикации — только один из возможных видов доказательств. Мы проверяем проекты, измеримые результаты, лидерство, независимые подтверждения и потенциал развития профиля. Если основы достаточно, строим план, который доводит реальные достижения до готового доказательственного кейса."], ["Аудит профиля показывает процент одобрения?", "Нет. Мы не выдаём псевдоточный процент. Результат показывает несколько программ, текущую основу профиля и вопросы, которые требуют документальной проверки."], ["Вы работаете только с готовыми кейсами?", "Нет. Если профиль пока не готов, составляем план на 3–12 месяцев: выбираем реальные профессиональные действия, фиксируем результат и собираем независимые подтверждения. Это может сохранить даже талант-маршрут, но не гарантирует одобрение."], ["Как работает гарантия при отказе?", "Стоимость полного сопровождения делится на 40%, 30% и 30%. При отказе мы возвращаем второй платёж 30%, а финальные 30% не выставляем. Оплаченной остаётся стартовая часть 40% за уже выполненную стратегию и подготовку; точные условия закрепляются в договоре."], ["Кто отвечает за юридические вопросы конкретной страны?", "Samotsvet ведёт стратегию и подготовку проекта. Когда вопрос требует лицензированного специалиста соответствующей юрисдикции, мы подключаем профильного партнёра и заранее объясняем его роль."], ["Можно ли сравнить несколько стран?", "Да. Сопоставляем итоговый статус, срок, зависимость от работодателя или бизнеса, положение семьи и реальные доказательства в Вашей ситуации."]]},
    closing: ["Первый шаг", "Получите карту программ и готовности профиля", "Ответьте на вопросы об опыте, результате и доказательствах. Расчёт происходит в браузере; страна не определяет итог автоматически.", "Пройти аудит профиля"],
  },
  en: {
    hero: ["With Nikita Samotsvetov's expertise", "Your relocation is our project", "You focus on work, business and family. I compare routes and assess the foundation of the case; the team manages profile development, evidence, documents, specialist partners and filing.", "Review my case", "Compare routes", "The audit takes 4–6 minutes · result shown on screen · reply within one business day", "10,000+ profiles since 2021 · 800+ matters · 200+ UK matters"],
    founder: ["Nikita Samotsvetov", "Founder of Samotsvet", "LLM International Law and Global Governance", "University of Leeds · 2023"],
    delegation: { eyebrow: "Relocation can be delegated", title: "What remains with you", body: "One detailed conversation about your experience, usually lasting 90–120 minutes. Signatures where they are genuinely required and decisions at the key project stages.", note: "Understanding criteria, preparing references, reconciling dates and facts across documents, monitoring rule changes and co-ordinating specialist partners are our responsibility. You receive concise progress reports.", items: ["Experience interview", "Signatures", "Key decisions"] },
    audiences: { eyebrow: "Who we help", title: "We start with your circumstances, not a country", intro: "The same experience may support several programmes. I compare the objective, required status, timing and facts that can be evidenced; the team turns the conclusion into a working plan.", items: [["01", "Specialists and senior leaders", "We distinguish personal contribution to products, teams and commercial outcomes from ordinary responsibilities."], ["02", "Founders and entrepreneurs", "We compare achievement, start-up and investment routes and connect the founder's role to business outcomes."], ["03", "Researchers and authors", "We bring academic, professional and independent recognition into one verifiable trajectory."], ["04", "Remote professionals and families", "We review working arrangements, contracts, income, family documents and the effects of the selected status."]]},
    problem: { eyebrow: "Why strong experience is not enough on its own", title: "A case loses credibility in the gaps between facts", body: "A strong career does not turn into evidence automatically. In my review, I look for points where a personal role disappears inside a team result, figures conflict across documents or external coverage fails to establish contribution. The team resolves those gaps before filing.", items: [["Personal contribution", "We show what the applicant did and how their decisions connect to the outcome."], ["Independent context", "We separate internal company evidence from recognition outside it."], ["Consistency", "We reconcile dates, roles, metrics and units across the full record."]]},
    development: { eyebrow: "A profile can be developed", title: "No publications at the outset does not necessarily close the route", body: "I do more than assess an already finished profile. If evidence is insufficient, we build a 3–12 month plan: select genuine projects and professional activity, define measurable outcomes and record the sources that can verify them.", note: "The aim is not to manufacture visibility. It is to bring real experience to a point at which it can be presented consistently and honestly.", link: "How profile development works", items: [["01", "Find the foundation", "Review projects, decisions, increasing responsibility and outcomes already present in the career or business."], ["02", "Map the gaps", "Identify missing independent assessment, public record, referees, metrics or new results."], ["03", "Create verifiable outcomes", "Plan speaking, authorship, expert roles and projects that genuinely continue the professional trajectory."], ["04", "Capture the evidence", "Record the outcome, personal contribution, scale and independent source before detail is lost."]]},
    compare: { eyebrow: "Route flexibility", title: "We do not sell a country", intro: "I begin with the objective, timing, dependence on an employer and the position of the family. I then test the same experience against several programmes; a preferred country does not determine the conclusion by itself.", link: "Open the full comparison", rows: [["UK", "Global Talent", "A career without one employer sponsor", "Recognition, contribution and independent evidence"], ["UK", "Innovator Founder", "Build an innovative start-up", "A new idea, viability and scalability"], ["US", "EB-1A", "Permanent status through extraordinary ability", "Sustained recognition and high-level achievement"], ["US", "EB-2 NIW", "Permanent status through a US national-interest endeavour", "A future plan and the ability to advance it"], ["US", "O-1", "Temporary work through a professional profile", "Achievements and a US petitioner"], ["US", "E-2", "Run an investment business", "Investment, an operating business and control"], ["ES", "Digital Nomad", "Residence for remote work", "Work, contracts, income and insurance"], ["FR", "Talent — innovative project", "Work on a recognised innovative project", "The project, host company and sufficient resources"], ["FR", "Talent — business creation", "Establish a commercial project in France", "A credible plan, resources and the founder's role"]]},
    services: { eyebrow: "Ways to work with us", title: "From the first comparison to filing and later status stages", intro: "A project may begin with one defined task or continue through the full cycle with one team. Scope and boundaries are agreed before paid work begins.", link: "View all working formats", items: [["01", "Profile audit", "Several potential programmes, the present foundation and questions requiring deeper review.", "Free · one business day"], ["02", "Route comparison", "A matrix of outcomes, timing, restrictions and evidential tasks.", "A standalone strategic deliverable"], ["03", "Evidence audit", "A criteria map, register of strong facts, weaknesses and preparation plan.", "For a selected route"], ["04", "Profile development", "A 3–12 month plan and a system for recording new outcomes.", "Where the profile is not yet ready"], ["05", "Full support", "Strategy, evidence, references, forms, partners and filing.", "UK from €5,000 · US from €8,000"], ["06", "Extensions and family", "The next status, family filing, extension and related documents.", "Following the main decision"]]},
    process: { eyebrow: "How we work", title: "Four deliverables rather than a long list of actions", items: [["01", "Route map", "We compare status, timing, restrictions and the position of the family."], ["02", "Evidence matrix", "Each central proposition is connected to a fact, source and criterion."], ["03", "Preparation plan", "We record gaps, tasks, owners and review dates."], ["04", "Reconciled bundle", "We check facts across documents and manage the agreed filing scope."]]},
    articles: { eyebrow: "What changed", title: "We distinguish a court ruling from its practical implementation", all: "All articles", read: "Review the change", items: [["United States · 27 August 2026", "Court vacates the immigrant-visa pause: what is known", "Why this was not a Supreme Court judgment and what still requires checking before an EB-1A or NIW consular stage.", "/en/blog/us-immigrant-visa-issuance-pause-russia/"], ["United Kingdom · 6 March 2026", "HC 1691: why the filing date determines which rules apply", "A timetable for the key changes.", "/en/blog/uk-hc-1691-dates/"], ["Spain · 20 February 2026", "The 2026 DNV income threshold and family calculation", "The 200%, 75% and 25% calculation following the SMI increase.", "/en/blog/spain-dnv-income-2026/"]]},
    pricing: ["Fees and timing", "The final budget depends on the route and present readiness", "Following the profile audit, we establish whether the matter needs a standalone strategy, profile development or full support. Scope, timing and fee are agreed in writing before paid work begins.", "Fees cover Samotsvet's work. Government fees, translations, licensed partners and other external costs are quoted separately unless expressly included."],
    guarantee: { eyebrow: "A guarantee of work, not an authority's decision", title: "No one can guarantee approval. We guarantee the quality of our work", body: "Before the project begins, you receive a reasoned assessment based on the documents and official criteria. An independent specialist also reviews the strategy. Scope, fee and payment schedule are fixed in advance and change only if the parties agree to change the scope.", request: "We respond to an authority's request without an additional professional fee. After a refusal, we prepare one repeat filing without charging for our work; government fees, translations and other external costs remain separate.", stages: [["40%", "At the start", "Strategy and preparation"], ["30%", "After filing", "Refunded after a refusal"], ["30%", "After approval", "Not charged after a refusal"]], refusal: "If the authority refuses the application, we refund the second payment, equal to 30% of the fee. The final 30% is not invoiced. The amount ultimately retained is the initial 40%, covering strategy and preparation already completed.", condition: "The guarantee applies where the client provides accurate information, follows the agreed strategy and performs their contractual obligations. The exact terms and refund period are recorded in the agreement before the first payment.", link: "Full working terms" },
    faq: { eyebrow: "Common questions", title: "What to understand before a project begins", items: [["Can I approach you without publications or speaking experience?", "Yes. Publications are only one possible form of evidence. We examine projects, measurable outcomes, leadership, independent evidence and the scope to develop the profile. Where the foundation is sufficient, we build a plan that turns genuine achievements into a filing-ready evidential case."], ["Does the profile audit provide an approval percentage?", "No. We do not produce a spurious percentage. The result identifies several potential programmes, the present foundation and questions requiring documentary review."], ["Do you only work with filing-ready cases?", "No. Where the profile is not ready, we build a 3–12 month plan around genuine professional activity, recorded outcomes and independent evidence. This can keep a talent route in consideration, but it does not guarantee approval."], ["How does the guarantee work after a refusal?", "The full-support fee is divided into 40%, 30% and 30%. After a refusal, we refund the second 30% payment and do not invoice the final 30%. The initial 40% remains paid for strategy and preparation already completed; the precise terms are recorded in the agreement."], ["Who handles jurisdiction-specific legal questions?", "Samotsvet leads strategy and project preparation. Where a matter requires a licensed professional in the relevant jurisdiction, we involve a specialist partner and explain their role in advance."], ["Can you compare several countries?", "Yes. We compare the eventual status, timing, dependence on employment or business, family position and evidence available in your circumstances."]]},
    closing: ["First step", "Receive a map of programmes and profile readiness", "Answer questions about experience, outcomes and evidence. The result is calculated in your browser; a preferred country does not determine it automatically.", "Start the profile audit"],
  },
} as const;

export function HomePage({ locale = "ru" }: { locale?: Locale }) {
  const text = copy[locale];
  const isEnglish = locale === "en";
  const base = isEnglish ? "/en" : "";
  const assessmentPath = withTrailingSlash(`${base}/assessment`);
  const comparePath = withTrailingSlash(`${base}/compare`);
  const servicesPath = withTrailingSlash(`${base}/services`);
  const faqData = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: text.faq.items.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  const serviceData = { "@context": "https://schema.org", "@type": "ProfessionalService", "@id": `${SITE_URL}/#professional-service`, name: "Samotsvet", legalName: LEGAL_NAME, url: `${SITE_URL}${base || "/"}`, logo: `${SITE_URL}/samotsvet-logo.svg`, founder: { "@id": `${SITE_URL}/about/#nikita`, "@type": "Person", name: FOUNDER_NAME }, areaServed: ["United Kingdom", "Spain", "United States", "France"] };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceData) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqData) }} />
    <SiteHeader locale={locale} />
    <main>
      <section className="hero section-shell">
        <div className="hero-copy"><p className="eyebrow">{text.hero[0]}</p><h1>{text.hero[1]}</h1><p className="hero-lede">{text.hero[2]}</p><div className="hero-actions"><Link className="button button-primary" href={assessmentPath}>{text.hero[3]}</Link><Link className="button button-secondary" href={comparePath}>{text.hero[4]}</Link></div><p className="hero-response">{text.hero[5]}</p><p className="hero-note">{text.hero[6]}</p></div>
        <figure className="hero-founder">
          <div className="hero-founder-photo"><Image src="/nikita-founder-white-v3.webp" alt={text.founder[0]} width={1149} height={1368} priority sizes="(max-width: 980px) 100vw, 48vw" /></div>
          <figcaption><strong>{text.founder[0]}</strong><span>{text.founder[1]}</span><small>{text.founder[2]}<br />{text.founder[3]}</small></figcaption>
        </figure>
      </section>

      <section className="delegation-band"><div className="section-shell delegation-layout"><div><p className="eyebrow eyebrow-light">{text.delegation.eyebrow}</p><h2>{text.delegation.title}</h2><p>{text.delegation.body}</p></div><div><div className="delegation-items">{text.delegation.items.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div><p>{text.delegation.note}</p></div></div></section>

      <section className="section-shell section-block audience-section"><Heading eyebrow={text.audiences.eyebrow} title={text.audiences.title} intro={text.audiences.intro} /><div className="audience-grid">{text.audiences.items.map(([n,t,b]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>

      <section className="problem-band"><div className="section-shell problem-layout"><div><p className="eyebrow eyebrow-light">{text.problem.eyebrow}</p><h2>{text.problem.title}</h2><p>{text.problem.body}</p></div><div className="problem-list">{text.problem.items.map(([t,b]) => <article key={t}><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>

      <section className="section-shell section-block development-evidence"><Heading eyebrow={text.development.eyebrow} title={text.development.title} intro={text.development.body} /><p className="development-note">{text.development.note}</p><div className="development-steps">{text.development.items.map(([n,t,b]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div><Link className="text-link" href={withTrailingSlash(`${base}/profile-development`)}>{text.development.link} <span aria-hidden="true">↗</span></Link></section>

      <section className="comparison-preview" id="directions"><div className="section-shell section-block"><Heading eyebrow={text.compare.eyebrow} title={text.compare.title} intro={text.compare.intro} /><div className="comparison-preview-grid">{text.compare.rows.map(([code,name,outcome,evidence]) => <article key={`${code}-${name}`}><span>{code}</span><h3>{name}</h3><strong>{outcome}</strong><p>{evidence}</p></article>)}</div><Link className="button button-secondary comparison-link" href={comparePath}>{text.compare.link}</Link></div></section>

      <section className="section-shell section-block services-section" id="services"><Heading eyebrow={text.services.eyebrow} title={text.services.title} intro={text.services.intro} /><div className="service-card-grid">{text.services.items.map(([n,t,b,m]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p><strong>{m}</strong></article>)}</div><Link className="text-link" href={servicesPath}>{text.services.link} <span aria-hidden="true">↗</span></Link></section>

      <ClientResults locale={locale} />

      <section className="section-shell section-block compact-process" id="process"><Heading eyebrow={text.process.eyebrow} title={text.process.title} /><ol>{text.process.items.map(([n,t,b]) => <li key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></li>)}</ol></section>

      <section className="editorial-section"><div className="section-shell section-block"><div className="section-heading"><div><p className="eyebrow">{text.articles.eyebrow}</p><h2>{text.articles.title}</h2></div><Link className="text-link" href={withTrailingSlash(`${base}/blog`)}>{text.articles.all} <span aria-hidden="true">↗</span></Link></div><div className="article-grid">{text.articles.items.map(([tag,title,body,href]) => <article className="article-card" key={href}><p className="article-tag">{tag}</p><h3>{title}</h3><p>{body}</p><Link href={href}>{text.articles.read} <span aria-hidden="true">→</span></Link></article>)}</div></div></section>

      <section className="section-shell pricing-strip" id="pricing"><div><p className="eyebrow">{text.pricing[0]}</p><h2>{text.pricing[1]}</h2></div><div><p>{text.pricing[2]}</p><small className="pricing-note">{text.pricing[3]}</small></div><div className="price-grid">{SERVICE_PRICES.map(item => <div className="price-item" key={item.code}><span>{isEnglish ? item.countryEn : item.countryRu}</span><strong>{isEnglish ? item.priceEn : item.price}</strong><small>{isEnglish ? "Preparation" : "Подготовка"}: {isEnglish ? item.timelineEn : item.timelineRu}</small>{isEnglish && "noteEn" in item ? <small>{item.noteEn}</small> : !isEnglish && "noteRu" in item ? <small>{item.noteRu}</small> : null}</div>)}</div></section>

      <section className="guarantee-section" id="guarantee"><div className="section-shell guarantee-layout"><div className="guarantee-heading"><p className="eyebrow eyebrow-light">{text.guarantee.eyebrow}</p><h2>{text.guarantee.title}</h2><p>{text.guarantee.body}</p><p>{text.guarantee.request}</p><Link className="button button-gold" href={withTrailingSlash(`${base}/legal`)}>{text.guarantee.link}</Link></div><div><div className="guarantee-stages">{text.guarantee.stages.map(([amount, moment, scope], index) => <article key={amount}><span>{String(index + 1).padStart(2, "0")}</span><strong>{amount}</strong><h3>{moment}</h3><p>{scope}</p></article>)}</div><div className="guarantee-refusal"><strong>{isEnglish ? "If the authority refuses" : "Если ведомство отказывает"}</strong><p>{text.guarantee.refusal}</p></div><small>{text.guarantee.condition}</small></div></div></section>

      <section className="section-shell section-block faq-section"><Heading eyebrow={text.faq.eyebrow} title={text.faq.title} /><div className="faq-list">{text.faq.items.map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>

      <PressMentions locale={locale} />

      <section className="section-shell closing-cta"><div><p className="eyebrow eyebrow-light">{text.closing[0]}</p><h2>{text.closing[1]}</h2></div><div><p>{text.closing[2]}</p><Link className="button button-gold" href={assessmentPath}>{text.closing[3]}</Link></div></section>
    </main>
    <SiteFooter locale={locale} />
  </>;
}

function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className={`section-heading${intro ? "" : " compact-heading"}`}><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{intro ? <p>{intro}</p> : null}</div>;
}
