import { ConsultationLink } from "./ConsultationLink";
import { SiteFooter } from "./SiteFooter";
import { SiteHeader } from "./SiteHeader";
import { SERVICE_PRICES, SITE_URL } from "../site";

type Locale = "ru" | "en";

const services = {
  ru: [
    { name: "Бесплатная первичная консультация", forWhom: "Для первого обращения и выбора следующего шага", result: "Предварительно определим подходящие варианты и объясним, как двигаться дальше", includes: ["До 20 минут с Никитой Самоцветовым", "Обсуждение цели, исходной ситуации и ограничений", "Предварительное сравнение подходящих программ", "Рекомендация следующего шага"], boundary: "До разговора не нужно готовить комплект документов. Подробная проверка материалов и письменная стратегия выполняются отдельно", fee: "Бесплатно" },
    { name: "Аудит профиля", forWhom: "Когда нужен подробный вывод по документам и доказательствам", result: "Письменная стратегия, карта критериев и план подготовки", includes: ["Разбор резюме и предоставленных материалов", "Сопоставление фактов с несколькими программами", "Проверка личного вклада и независимых источников", "Сильные стороны, пробелы и приоритеты подготовки"], boundary: "Состав документов, срок, результат и цена согласуются до начала платной работы", fee: "Объем и цена фиксируются заранее" },
    { name: "Развитие профиля", forWhom: "Когда до подачи есть 3–12 месяцев, а доказательств пока недостаточно", result: "Реалистичный план профессиональных действий и система фиксации результатов", includes: ["Цели по критериям выбранного маршрута", "Проекты, авторские материалы, выступления и экспертные роли", "Измеримые результаты и контрольные точки", "Подготовка источников и рекомендателей"], boundary: "В план входят реальные профессиональные действия и проверяемые результаты. Отсутствие публикаций само по себе не закрывает путь к визе таланта", fee: "Программа рассчитывается после первичной консультации" },
    { name: "Полное сопровождение", forWhom: "Когда нужен один ответственный контур от стратегии до подачи", result: "Согласованный комплект и сопровождение процесса в утвержденном объеме", includes: ["Стратегия и календарь", "Подготовка доказательств и рекомендаций", "Формы и сопроводительные материалы", "Координация переводов и профильных партнеров", "Финальная проверка и сопровождение подачи"], boundary: "Одобрение не гарантируется. Условия проверки стратегии, работы с запросом ведомства, повторной подачи и возврата второго платежа фиксируются в договоре", fee: "UK от €5 000 · US от €8 000 · ES от €1 600 · FR от €6 000" },
  ],
  en: [
    { name: "Free initial consultation", forWhom: "For an initial enquiry and selection of the next step", result: "A preliminary view of suitable options and a clear next step", includes: ["Up to 20 minutes with Nikita Samotsvetov", "Discussion of your objective, circumstances and constraints", "A preliminary comparison of suitable programmes", "Recommendation of the next step"], boundary: "You do not need to prepare a full document bundle before the conversation. A detailed review and written strategy are separate services", fee: "Free" },
    { name: "Profile audit", forWhom: "Where a detailed view of the documents and evidence is required", result: "A written strategy, criteria map and preparation plan", includes: ["Review of the CV and supplied material", "Matching the facts to several programmes", "Personal contribution and independent source review", "Strengths, gaps and preparation priorities"], boundary: "The documents, timetable, deliverable and fee are agreed before paid work begins", fee: "Scope and fee fixed in advance" },
    { name: "Profile development", forWhom: "Where 3–12 months remain before filing and evidence is insufficient", result: "A realistic professional plan and a system for recording outcomes", includes: ["Objectives linked to the selected route", "Projects, authorship, speaking and expert roles", "Measurable outcomes and review points", "Source and referee preparation"], boundary: "The plan is based on genuine professional activity and verifiable results. A lack of publications does not by itself rule out a talent visa", fee: "Quoted following the initial consultation" },
    { name: "Full support", forWhom: "Where one accountable team is required from strategy to filing", result: "A reconciled bundle and management of the agreed process", includes: ["Strategy and timetable", "Evidence and reference preparation", "Forms and supporting material", "Translation and specialist partner co-ordination", "Final review and filing support"], boundary: "Approval is not guaranteed. The independent strategy review, response to an authority, repeat filing and refund of the second payment are governed by the agreement", fee: "UK from €5,000 · US from €8,000 · ES from €1,600 · FR from €6,000" },
  ],
} as const;

export function ServicesPage({ locale = "ru" }: { locale?: Locale }) {
  const en = locale === "en";
  const schema = { "@context": "https://schema.org", "@type": "ItemList", itemListElement: services[locale].map((service, index) => ({ "@type": "ListItem", position: index + 1, item: { "@type": "Service", name: service.name, provider: { "@type": "ProfessionalService", name: "Samotsvet", url: SITE_URL }, description: service.result } })) };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <SiteHeader locale={locale} />
    <main>
      <section className="inner-hero section-shell services-hero"><div><p className="eyebrow">{en ? "Services" : "Форматы работы"}</p><h1>{en ? "From a free consultation to the complete preparation cycle" : "От бесплатной консультации до полного цикла подготовки"}</h1></div><p>{en ? "Each paid stage has a practical deliverable, clear boundary and agreed fee. We recommend only the level of work required for the next responsible decision." : "У каждого платного этапа есть практический результат, понятные границы и согласованная стоимость. Мы рекомендуем объем работы, необходимый для следующего ответственного решения."}</p></section>
      <section className="section-shell services-page-list">{services[locale].map((service, index) => <article key={service.name} id={`service-${index + 1}`}><div className="service-page-title"><span>{String(index + 1).padStart(2, "0")}</span><h2>{service.name}</h2><p>{service.forWhom}</p></div><div className="service-page-content"><h3>{en ? "Deliverable" : "Результат"}</h3><p>{service.result}</p><h3>{en ? "Included" : "Что входит"}</h3><ul>{service.includes.map(item => <li key={item}>{item}</li>)}</ul><p className="service-boundary"><strong>{en ? "Boundary: " : "Граница: "}</strong>{service.boundary}</p><p className="service-fee">{service.fee}</p></div></article>)}</section>
      <section className="section-shell service-country-fees"><div><p className="eyebrow">{en ? "Full-support starting fees" : "Стартовая стоимость полного сопровождения"}</p><h2>{en ? "The country and readiness determine the final scope" : "Страна и готовность определяют итоговый объем"}</h2></div><div className="price-grid">{SERVICE_PRICES.map(item => <div className="price-item" key={item.code}><span>{en ? item.countryEn : item.countryRu}</span><strong>{en ? item.priceEn : item.price}</strong><small>{en ? item.timelineEn : item.timelineRu}</small></div>)}</div></section>
      <section className="section-shell closing-cta"><div><p className="eyebrow eyebrow-light">{en ? "Initial consultation" : "Первичная консультация"}</p><h2>{en ? "Discuss your circumstances and the next step" : "Обсудим Вашу ситуацию и следующий шаг"}</h2></div><div><p>{en ? "Complete five short fields. We will contact you within one working day to arrange a free consultation with Nikita Samotsvetov." : "Заполните пять коротких полей. Свяжемся с Вами в течение рабочего дня, чтобы согласовать бесплатную консультацию с Никитой Самоцветовым."}</p><ConsultationLink className="button button-gold" locale={locale} location="services_final" /></div></section>
    </main>
    <SiteFooter locale={locale} />
  </>;
}
