import Link from "next/link";
import { SiteFooter } from "./SiteFooter";
import { SiteHeader } from "./SiteHeader";
import { SERVICE_PRICES, SITE_URL, withTrailingSlash } from "../site";

type Locale = "ru" | "en";

const services = {
  ru: [
    { name: "Аудит профиля", forWhom: "Для первого обращения и выбора следующего шага", result: "Несколько возможных программ, текущая основа и перечень вопросов для углублённой проверки", includes: ["Аудит цели, опыта и исходной ситуации", "Сопоставление одних фактов с несколькими программами", "Сильные стороны и направления развития", "Рекомендация следующего формата работы"], boundary: "Не включает проверку документов и не является заключением о вероятности одобрения", fee: "Бесплатно · ответ в течение одного рабочего дня" },
    { name: "Сравнение маршрутов", forWhom: "Когда подходят несколько стран или программ", result: "Матрица вариантов и обоснованная рекомендация", includes: ["Итоговый статус и долгосрочная цель", "Сроки, ограничения и положение семьи", "Доказательственная задача каждого варианта", "Последовательность возможных подач"], boundary: "Опирается на предоставленные факты; проверка полного комплекта выполняется отдельно", fee: "Стоимость фиксируется после аудита профиля" },
    { name: "Аудит доказательной базы", forWhom: "Когда маршрут выбран, но готовность комплекта неясна", result: "Карта критериев, реестр сильных фактов и план пробелов", includes: ["Разбор резюме и предоставленных материалов", "Матрица «тезис — факт — источник — критерий»", "Проверка личного вклада и независимого контекста", "Приоритеты подготовки и список недостающих материалов"], boundary: "Не включает создание новых достижений, финальную сборку и подачу", fee: "Объем и цена фиксируются до начала аудита" },
    { name: "Развитие профиля", forWhom: "Когда до подачи есть 3–12 месяцев, а доказательств пока недостаточно", result: "Реалистичный план профессиональных действий и система фиксации результатов", includes: ["Цели по критериям выбранного маршрута", "Проекты, авторские материалы, выступления и экспертные роли", "Измеримые результаты и контрольные точки", "Подготовка источников и рекомендателей"], boundary: "Мы не покупаем фиктивные публикации, награды или формальное признание", fee: "Программа рассчитывается после аудита" },
    { name: "Полное сопровождение", forWhom: "Когда нужен один ответственный контур от стратегии до подачи", result: "Согласованный комплект и сопровождение процесса в утвержденном объеме", includes: ["Стратегия и календарь", "Подготовка доказательств и рекомендаций", "Формы и сопроводительные материалы", "Координация переводов и профильных партнеров", "Финальная проверка и сопровождение подачи"], boundary: "Одобрение не гарантируется. Гарантия качества работы, запрос ведомства и условия возврата 30% фиксируются в договоре", fee: "UK от €5 000 · US от €8 000 · ES от €1 600 · FR от €6 000" },
    { name: "Следующий статус и семья", forWhom: "После основной подачи или решения", result: "План зависимых заявителей, продления или следующего статуса", includes: ["Синхронизация семейных документов", "Подготовка к интервью, если применимо", "Проверка требований к продлению", "Сохранение доказательственной истории"], boundary: "Состав зависит от страны, категории и роли лицензированного партнера", fee: "Стоимость определяется по задаче" },
  ],
  en: [
    { name: "Profile audit", forWhom: "For an initial enquiry and selection of the next step", result: "Several potential programmes, the present foundation and questions for deeper review", includes: ["Audit of the objective, experience and starting position", "Matching the same facts to several programmes", "Current strengths and development priorities", "Recommendation of the next working format"], boundary: "Does not include document review and is not an approval-probability opinion", fee: "Free · reply within one business day" },
    { name: "Route comparison", forWhom: "Where several countries or programmes may fit", result: "A comparison matrix and reasoned recommendation", includes: ["Eventual status and long-term objective", "Timing, restrictions and family position", "Evidential task for each option", "Possible filing sequence"], boundary: "Based on the facts supplied; full document review is separate", fee: "The fee is fixed following the profile audit" },
    { name: "Evidence audit", forWhom: "Where the route is selected but bundle readiness is unclear", result: "A criteria map, register of strong facts and gap plan", includes: ["Review of the CV and supplied material", "Matrix of proposition, fact, source and criterion", "Personal contribution and independent context review", "Preparation priorities and missing-material list"], boundary: "Does not include creating new achievements, final assembly or filing", fee: "Scope and fee are fixed before the audit begins" },
    { name: "Profile development", forWhom: "Where 3–12 months remain before filing and evidence is insufficient", result: "A realistic professional plan and a system for recording outcomes", includes: ["Objectives linked to the selected route", "Projects, authorship, speaking and expert roles", "Measurable outcomes and review points", "Source and referee preparation"], boundary: "We do not purchase fabricated publications, awards or nominal recognition", fee: "The programme is quoted after the audit" },
    { name: "Full support", forWhom: "Where one accountable team is required from strategy to filing", result: "A reconciled bundle and management of the agreed process", includes: ["Strategy and timetable", "Evidence and reference preparation", "Forms and supporting material", "Translation and specialist partner co-ordination", "Final review and filing support"], boundary: "Approval is not guaranteed. The work-quality guarantee, response to an authority and 30% refund terms are recorded in the agreement", fee: "UK from €5,000 · US from €8,000 · ES from €1,600 · FR from €6,000" },
    { name: "Next status and family", forWhom: "Following the principal filing or decision", result: "A plan for dependants, extension or the next status", includes: ["Family-document co-ordination", "Interview preparation where relevant", "Extension requirement review", "Preservation of the evidential history"], boundary: "Scope depends on the country, category and role of the licensed partner", fee: "Quoted for the particular task" },
  ],
} as const;

export function ServicesPage({ locale = "ru" }: { locale?: Locale }) {
  const en = locale === "en";
  const base = en ? "/en" : "";
  const schema = { "@context": "https://schema.org", "@type": "ItemList", itemListElement: services[locale].map((service, index) => ({ "@type": "ListItem", position: index + 1, item: { "@type": "Service", name: service.name, provider: { "@type": "ProfessionalService", name: "Samotsvet", url: SITE_URL }, description: service.result } })) };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <SiteHeader locale={locale} />
    <main>
      <section className="inner-hero section-shell services-hero"><div><p className="eyebrow">{en ? "Services" : "Форматы работы"}</p><h1>{en ? "One defined task or the full preparation cycle" : "От отдельной задачи до полного цикла подготовки"}</h1></div><p>{en ? "Each stage has a practical deliverable, boundary and agreed fee. A project begins with the smallest level of work needed to make a responsible decision." : "У каждого этапа есть практический результат, границы и согласованная стоимость. Проект начинается с минимального объема работы, достаточного для ответственного решения."}</p></section>
      <section className="section-shell services-page-list">{services[locale].map((service, index) => <article key={service.name} id={`service-${index + 1}`}><div className="service-page-title"><span>{String(index + 1).padStart(2,"0")}</span><h2>{service.name}</h2><p>{service.forWhom}</p></div><div className="service-page-content"><h3>{en ? "Deliverable" : "Результат"}</h3><p>{service.result}</p><h3>{en ? "Included" : "Что входит"}</h3><ul>{service.includes.map(item => <li key={item}>{item}</li>)}</ul><p className="service-boundary"><strong>{en ? "Boundary: " : "Граница: "}</strong>{service.boundary}</p><p className="service-fee">{service.fee}</p></div></article>)}</section>
      <section className="section-shell service-country-fees"><div><p className="eyebrow">{en ? "Full-support starting fees" : "Стартовая стоимость полного сопровождения"}</p><h2>{en ? "The country and readiness determine the final scope" : "Страна и готовность определяют итоговый объем"}</h2></div><div className="price-grid">{SERVICE_PRICES.map(item => <div className="price-item" key={item.code}><span>{en ? item.countryEn : item.countryRu}</span><strong>{en ? item.priceEn : item.price}</strong><small>{en ? item.timelineEn : item.timelineRu}</small></div>)}</div></section>
      <section className="section-shell closing-cta"><div><p className="eyebrow eyebrow-light">{en ? "Start small" : "Начните с малого"}</p><h2>{en ? "Establish the right level of work first" : "Сначала определим нужный уровень работы"}</h2></div><div><p>{en ? "The profile audit helps distinguish a short answer, a standalone evidence audit and a full project." : "Аудит профиля помогает отличить короткий ответ, отдельный аудит доказательств и полноценный проект."}</p><Link className="button button-gold" href={withTrailingSlash(`${base}/assessment`)}>{en ? "Start profile audit" : "Пройти аудит профиля"}</Link></div></section>
    </main>
    <SiteFooter locale={locale} />
  </>;
}
