import type { Article } from "./articles";

export const news2026En: Article[] = [
  {
    slug: "us-immigrant-visa-issuance-pause-russia",
    tag: "United States · Immigrant visas",
    title: "Court vacates the immigrant-visa pause: what it means for Russian nationals",
    description: "The 21 January to 26 August 2026 chronology: district-court judgment, disputed implementation and the effect on EB-1A and NIW.",
    reading: "6 min read",
    published: "2026-08-27",
    author: "Nikita Samotsvetov",
    lead: "On 21 January 2026, the US Department of State paused immigrant-visa issuance to Russian nationals. On 21 August, a federal district court in New York held the policy unlawful and vacated it. This was not a Supreme Court judgment, and practical implementation remained disputed on 26 August.",
    relatedCountry: "usa",
    sources: [
      { label: "Department of State — immigrant-visa issuance pause", href: "https://travel.state.gov/content/travel/en/News/visas-news/immigrant-visa-processing-updates-for-nationalities-at-high-risk-of-public-benefits-usage.html" },
      { label: "Department of State — September 2026 Visa Bulletin", href: "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin/2026/visa-bulletin-for-september-2026.html" },
      { label: "Department of State — immigrant-visa interview location", href: "https://travel.state.gov/content/travel/en/News/visas-news/adjudicating-iv-applicants-in-their-country-of-residence.html" },
      { label: "Federal district court — 21 August 2026 decision", href: "https://media.nilc.org/2026/04/CLINIC-v-Rubio-partial-MSJ-decision-08-21-2026.pdf" },
      { label: "CLINIC v. Rubio — case materials and updates", href: "https://www.nilc.org/litigation/clinic-v-rubio/" },
    ],
    sections: [
      { title: "21 January: what the Department of State paused", paragraphs: ["The measure concerned immigrant-visa issuance to nationals of 75 countries, including Russia. Applications and interviews could continue, but the final visa was not issued. Dual nationals applying with a passport of a country outside the list were exempt, and previously issued visas were not revoked.", "This was not a blanket pause on every green-card process. USCIS petitions and adjustment of status inside the United States are separate. O-1 and E-2 nonimmigrant visas were not covered by this particular measure."] },
      { title: "21 August: what the court decided", paragraphs: ["The federal district court for the Southern District of New York held the policy unlawful and vacated it in full. It also vacated refusals based solely on the policy.", "This was a first-instance federal judgment. It is incorrect to say that the US Supreme Court lifted the pause."] },
      { title: "26 August: why unconditional resumption would be premature", paragraphs: ["The plaintiffs filed an emergency enforcement motion alleging a continuing operational pause and cancelled interviews. That was a party's submission which the court still had to address.", "The accurate position is therefore that the policy was vacated by a court, while practical implementation must still be checked for the relevant consular post and case."] },
      { title: "What this changes for EB-1A and NIW", paragraphs: ["Approval of an I-140 petition, visa-number availability and consular issuance are separate questions. The judgment addresses the last barrier but does not replace a review of the category, priority date, interview location and personal circumstances.", "O-1 and E-2 remain separate nonimmigrant classifications with their own requirements."], points: ["Nationality and any second nationality", "Consular processing or adjustment of status", "Implementation status of the court judgment", "Country of residence and designated post"] },
    ],
  },
  {
    slug: "uk-hc-1691-dates",
    tag: "United Kingdom · 2026 changes",
    title: "HC 1691: why the filing date determines which rules apply",
    description: "The commencement timetable for the main changes in the UK HC 1691 package.",
    reading: "5 min read",
    published: "2026-03-06",
    author: "Nikita Samotsvetov",
    lead: "HC 1691 was published on 5 March 2026, but its provisions took effect on different dates. Both the text and the stage at which a change applies matter to an applicant.",
    relatedCountry: "uk",
    sources: [
      { label: "GOV.UK — Statement of Changes HC 1691", href: "https://www.gov.uk/government/publications/statement-of-changes-to-the-immigration-rules-hc-1619-5-march-2026" },
      { label: "GOV.UK — Explanatory Memorandum to HC 1691", href: "https://www.gov.uk/government/publications/statement-of-changes-to-the-immigration-rules-hc-1619-5-march-2026/explanatory-memorandum-to-the-statement-of-changes-in-the-immigration-rules-hc-1691-5-march-2026-accessible" },
      { label: "GOV.UK — Immigration Rules updates", href: "https://www.gov.uk/guidance/immigration-rules/updates" },
    ],
    sections: [
      { title: "One package with several commencement dates", paragraphs: ["Some changes took effect on 26 March and 8 April 2026. The extension of Global Talent to additional design roles started on 1 July 2026. The new B2 English requirement for settlement on a number of routes applies to applications made from 26 March 2027.", "A reference to the March document without its commencement date may therefore be misleading. We check the operative version of the rule together with its transitional provisions."] },
      { title: "Dates to record in the plan", paragraphs: ["Record the date of the original grant, the next extension and the intended settlement application separately. A different version of the rules may apply at each stage."], points: ["Route and date of the current permission", "Planned date of the next application", "Language requirement at that particular stage", "Transitional provisions for people already on the route"] },
      { title: "Practical conclusion", paragraphs: ["The filing date is now a distinct element of the strategy. A general summary of the reform does not establish which requirements will apply to a particular application."] },
    ],
  },
  {
    slug: "uk-global-talent-design-pathway",
    tag: "United Kingdom · Global Talent",
    title: "Global Talent for designers: what changed in practice",
    description: "The design pathway introduced on 1 July 2026 and the distinction between a portfolio and evidence of recognition.",
    reading: "5 min read",
    published: "2026-07-02",
    author: "Nikita Samotsvetov",
    lead: "From 1 July 2026, Global Talent covers additional design roles that did not previously fit within the existing fields. The established architecture and fashion routes remain in place.",
    relatedCountry: "uk",
    sources: [
      { label: "GOV.UK — Appendix Global Talent", href: "https://www.gov.uk/guidance/immigration-rules/immigration-rules-appendix-global-talent" },
      { label: "GOV.UK — HC 1691 explanation of the design pathway", href: "https://www.gov.uk/government/publications/statement-of-changes-to-the-immigration-rules-hc-1619-5-march-2026/explanatory-memorandum-to-the-statement-of-changes-in-the-immigration-rules-hc-1691-5-march-2026-accessible" },
    ],
    sections: [
      { title: "What opened on 1 July", paragraphs: ["The official wording covers additional design roles. Architecture and fashion already had separate Global Talent mechanisms before the new design pathway was introduced."] },
      { title: "A portfolio and independent recognition serve different purposes", paragraphs: ["A portfolio shows the quality of the work. An immigration matter also needs to establish the applicant's personal role, independent assessment and the significance of the result beyond their own team."], points: ["Who assessed the work independently of the employer", "What the applicant personally did in a team project", "Which measurable changes followed from the work"] },
      { title: "Evidence to prepare", paragraphs: ["We first create a proposition map showing which role, result and form of recognition each document supports. We then design the presentation and allocate the evidence to the relevant criteria."] },
    ],
  },
  {
    slug: "uk-earned-settlement-proposal",
    tag: "United Kingdom · Settlement",
    title: "The ten-year route to settlement has not yet become an operative rule",
    description: "Which elements of Earned Settlement remain proposals and which settlement periods currently apply.",
    reading: "4 min read",
    published: "2025-11-21",
    author: "Nikita Samotsvetov",
    lead: "Earned Settlement was published as a consultation model. Its proposed ten-year baseline did not itself become an operative rule.",
    relatedCountry: "uk",
    sources: [
      { label: "GOV.UK — Earned Settlement consultation", href: "https://www.gov.uk/government/consultations/earned-settlement/a-fairer-pathway-to-settlement-statement-and-accompanying-consultation-on-earned-settlement-accessible" },
      { label: "GOV.UK — current Global Talent settlement periods", href: "https://www.gov.uk/global-talent" },
    ],
    sections: [
      { title: "The current position", paragraphs: ["The GOV.UK Global Talent page continues to state that settlement may be available after three or five years, depending on the field and the basis on which permission was granted."] },
      { title: "The consultation proposal", paragraphs: ["The consultation model used a ten-year baseline with possible reductions for contribution, income and presence on particular routes. A seven-year reduction after three years of continuous residence was discussed for Global Talent and Innovator Founder.", "A consultation indicates a policy direction. It does not create a new entitlement or replace the Immigration Rules in force."] },
      { title: "How to plan", paragraphs: ["We separate two scenarios: the plan under current rules and a contingency calculation for possible reform. Neither a ten-year period nor the preservation of a three-year period can be promised on the basis of a consultation paper alone."] },
    ],
  },
  {
    slug: "uk-ilr-english-b2-2027",
    tag: "United Kingdom · English for settlement",
    title: "B2 for settlement: who should prepare for 26 March 2027",
    description: "The new English level for settlement under Global Talent, Innovator Founder and other routes.",
    reading: "4 min read",
    published: "2026-03-06",
    author: "Nikita Samotsvetov",
    lead: "The English requirement for settlement on a number of routes rises from B1 to B2. The change takes effect on 26 March 2027 and may affect people already progressing towards settlement.",
    relatedCountry: "uk",
    sources: [
      { label: "GOV.UK — HC 1691 Explanatory Memorandum, paragraphs 5.60–5.62", href: "https://www.gov.uk/government/publications/statement-of-changes-to-the-immigration-rules-hc-1619-5-march-2026/explanatory-memorandum-to-the-statement-of-changes-in-the-immigration-rules-hc-1691-5-march-2026-accessible" },
    ],
    sections: [
      { title: "Applications affected by the change", paragraphs: ["The official list includes Appendix KoLL, Skilled Worker, Global Talent, Scale-up, Innovator Founder, UK Ancestry and other routes. The rule applies to applications made from 26 March 2027."] },
      { title: "What to check in earlier language evidence", paragraphs: ["A document used to prove B1 on entry does not necessarily prove B2 at the settlement stage. Check the level recorded in the degree, test or other permitted evidence well in advance."] },
      { title: "A practical timetable", paragraphs: ["We recommend checking the basis of the language evidence before the final year on the route. If a new test is needed, the applicant then has time to choose an approved examination, prepare and obtain the result without putting the filing date at risk."] },
    ],
  },
  {
    slug: "spain-dnv-income-2026",
    tag: "Spain · Digital Nomad Visa",
    title: "Digital Nomad Visa: the 2026 income threshold and family calculation",
    description: "The current calculation using 200%, 75% and 25% of the Spanish SMI after Royal Decree 126/2026.",
    reading: "4 min read",
    published: "2026-02-20",
    author: "Nikita Samotsvetov",
    lead: "Spain's SMI for 2026 is €1,221 across 14 payments, or €17,094 a year. For the Digital Nomad Visa, the annual amount must be converted to an average monthly figure before applying the percentages for the principal applicant and family.",
    relatedCountry: "spain",
    sources: [
      { label: "BOE — Royal Decree 126/2026", href: "https://www.boe.es/buscar/act.php?id=BOE-A-2026-3815" },
      { label: "Spanish Ministry of Foreign Affairs — telework financial requirements", href: "https://www.exteriores.gob.es/Consulados/bogota/es/ServiciosConsulares/Paginas/index.aspx?scca=Visados&scco=Colombia&scd=31&scs=Visado+de+residencia+para+teletrabajo+%28n%C3%B3mada+digital%29" },
    ],
    sections: [
      { title: "The correct calculation base", paragraphs: ["Dividing €17,094 by 12 gives €1,424.50 a month. The principal applicant needs 200% of that amount, or €2,849 a month."] },
      { title: "Family members", paragraphs: ["The first family member adds 75% of the average monthly SMI, or €1,068.38. Each additional family member adds 25%, or €356.13. The calculated minimum for a family of three is €4,273.50 a month."], points: ["Principal applicant — €2,849", "First family member — €1,068.38", "Each additional family member — €356.13"] },
      { title: "Allowance for exchange-rate movement", paragraphs: ["Where income is received in another currency, meeting the minimum on one calculation date provides little resilience. We allow for currency movement and check that the amount is supported by contracts, receipts and bank records."] },
    ],
  },
  {
    slug: "spain-dnv-real-work",
    tag: "Spain · Digital Nomad Visa",
    title: "Spain examines the genuine remote work before filing",
    description: "The facts that support genuine and continuous activity for Spain's Digital Nomad Visa.",
    reading: "4 min read",
    published: "2026-08-06",
    author: "Nikita Samotsvetov",
    lead: "The official requirements for international telework cover the contract, the company's genuine and continuous activity, the remote nature of the work and a relationship with the applicant lasting at least three months.",
    relatedCountry: "spain",
    sources: [
      { label: "Official PRIE portal — Digital nomads", href: "https://prie.comercio.gob.es/es-es/Paginas/Teletrabajadores-caracter-internacional.aspx" },
      { label: "BOE — current consolidated Law 14/2013", href: "https://www.boe.es/buscar/act.php?id=BOE-A-2013-10074" },
    ],
    sections: [
      { title: "Three propositions to establish", paragraphs: ["The evidence should show that the overseas company genuinely operates, that the applicant's duties can be performed remotely and that the employment or professional relationship existed for at least three months before the application."] },
      { title: "Facts that must align", paragraphs: ["The contract, role, invoices, payments and description of day-to-day work should describe the same reality. A new high-value contract unsupported by payment movement or a history of the relationship is likely to create further questions."] },
      { title: "How we review the bundle", paragraphs: ["Before translation and apostille, we build a chronology: when the relationship began, which services or duties were performed, how payment changed and where the facts are recorded independently of the applicant's own account."] },
    ],
  },
  {
    slug: "spain-dnv-apply-from-spain",
    tag: "Spain · Digital Nomad Visa",
    title: "Can a Digital Nomad application be made from Spain?",
    description: "The difference between a consular visa and a three-year authorisation while lawfully present in Spain.",
    reading: "4 min read",
    published: "2026-08-07",
    author: "Nikita Samotsvetov",
    lead: "The current wording of Law 14/2013 allows a foreign national who is lawfully in Spain to apply for an international telework authorisation. Lawful status on the filing date is central.",
    relatedCountry: "spain",
    sources: [
      { label: "BOE — Article 74 quinquies of Law 14/2013", href: "https://www.boe.es/buscar/act.php?id=BOE-A-2013-10074" },
    ],
    sections: [
      { title: "The statutory wording", paragraphs: ["Article 74 quinquies expressly covers foreign nationals who are in Spain lawfully, as well as those who entered on the corresponding visa. The authorisation may be granted for up to three years."] },
      { title: "Consular and in-country procedures", paragraphs: ["A non-resident planning a move applies for a consular visa valid for up to one year. An applicant lawfully present in Spain applies for a residence authorisation. The circumstances and practical filing arrangements are different."] },
      { title: "What to examine before choosing", paragraphs: ["The lawful basis of stay, time remaining, place where documents will be obtained, social security and family bundle should be assessed together. The availability of an in-country application does not make it the best route for every applicant."] },
    ],
  },
  {
    slug: "uscis-statistics-how-to-read",
    tag: "United States · USCIS data",
    title: "The limits of applying USCIS statistics to an individual case",
    description: "How to read quarterly immigration-petition data without turning it into a false prediction of approval.",
    reading: "4 min read",
    published: "2026-08-08",
    author: "Nikita Samotsvetov",
    lead: "USCIS publishes quarterly data by form and category. The figures help to track workload and decisions at agency level, but they do not become a personal probability of approval.",
    relatedCountry: "usa",
    sources: [
      { label: "USCIS — Immigration and Citizenship Data", href: "https://www.uscis.gov/tools/reports-and-studies/immigration-and-citizenship-data" },
      { label: "USCIS — how processing times are calculated", href: "https://egov.uscis.gov/processing-times/more-info" },
    ],
    sections: [
      { title: "An average combines unlike matters", paragraphs: ["A single category contains applicants from different sectors with different histories and evidence quality. A quarterly approval rate does not show how persuasive one particular record is."] },
      { title: "Trends that can be monitored", paragraphs: ["It is useful to follow receipts, decisions, requests for evidence and the pending caseload. Quarterly movement also reflects the composition of filings, workload allocation and changes in reporting."] },
      { title: "How we use the data", paragraphs: ["Statistics provide planning context. Readiness is assessed from the applicant's facts, the category requirements and the quality of independent support."] },
    ],
  },
  {
    slug: "eb2-niw-not-simple-alternative",
    tag: "United States · EB-2 NIW",
    title: "EB-2 NIW: what the applicant must establish",
    description: "Why NIW examines the proposed work, national importance and the applicant's ability to advance the plan.",
    reading: "5 min read",
    published: "2026-08-09",
    author: "Nikita Samotsvetov",
    lead: "EB-1A and EB-2 NIW answer different questions. NIW requires the applicant to connect a defined proposed endeavour convincingly to the US national interest through its own three-part analysis.",
    relatedCountry: "usa",
    sources: [
      { label: "USCIS Policy Manual — EB-2 and National Interest Waiver", href: "https://www.uscis.gov/policy-manual/volume-6-part-f-chapter-5" },
      { label: "USCIS Policy Manual — Extraordinary Ability", href: "https://www.uscis.gov/policy-manual/volume-6-part-f-chapter-2" },
    ],
    sections: [
      { title: "What NIW examines", paragraphs: ["The current framework considers the substantial merit and national importance of the proposed endeavour, whether the applicant is well positioned to advance it and whether waiving the job offer and labour certification requirements would benefit the United States."] },
      { title: "Where the rationale breaks down", paragraphs: ["The broad importance of a sector does not establish the national importance of the applicant's own work. A phrase such as ‘develop artificial intelligence’ names a field but does not explain the task, outcome, resources or intended beneficiaries."], points: ["No specific plan of work", "Past results are disconnected from the proposed work", "No partners, resources or initial action", "The value of a sector substitutes for the importance of the specific project"] },
      { title: "Comparison with EB-1A", paragraphs: ["We compare the available evidence with the task set by each category. Sustained past recognition may work more strongly for EB-1A, while a specific project already being advanced and capable of wider benefit may fit NIW more closely."] },
    ],
  },
  {
    slug: "eb1a-processing-times-planning",
    tag: "United States · EB-1A",
    title: "How to use the EB-1A processing time in a relocation plan",
    description: "How USCIS calculates processing time and why a relocation plan needs more than one scenario.",
    reading: "4 min read",
    published: "2026-08-10",
    author: "Nikita Samotsvetov",
    lead: "The USCIS processing-time figure is the period in which the agency completed 80% of adjudicated cases over the previous six months. It is a retrospective metric, not a deadline for an individual petition.",
    relatedCountry: "usa",
    sources: [
      { label: "USCIS — Case Processing Times", href: "https://egov.uscis.gov/processing-times" },
      { label: "USCIS — information about processing times", href: "https://egov.uscis.gov/processing-times/more-info" },
      { label: "USCIS — Premium Processing", href: "https://www.uscis.gov/forms/all-forms/how-do-i-request-premium-processing" },
    ],
    sections: [
      { title: "Why the figure changes", paragraphs: ["The metric changes with the set of completed cases. An individual request for evidence, workload transfer or the circumstances of a particular office are reflected only once the relevant cases enter the completed sample."] },
      { title: "Changes during the waiting period", paragraphs: ["Employment, country of residence, family circumstances and current evidence may change while a petition is pending. An immigration petition should therefore not be the only calendar used for a relocation plan."] },
      { title: "Standard and premium processing", paragraphs: ["Premium Processing is available for certain classifications, but the period and type of USCIS action depend on the category. Faster adjudication does not reduce the requirements or guarantee approval; the current Form I-907 instructions should be checked before filing."] },
    ],
  },
  {
    slug: "us-immigrant-worker-rulemaking",
    tag: "United States · Proposed rules",
    title: "Future EB-1A and NIW rulemaking: the current position",
    description: "The status of the DHS project to modernise requirements for employment-based petitions.",
    reading: "4 min read",
    published: "2025-09-23",
    author: "Nikita Samotsvetov",
    lead: "The federal regulatory agenda includes a Petition for Immigrant Worker Reforms project intended to clarify requirements for EB-1A, EB-2 NIW and other employment-based categories. Its Unified Agenda entry described planned rulemaking, not an operative rule.",
    relatedCountry: "usa",
    sources: [
      { label: "Reginfo.gov — RIN 1615-AC85", href: "https://www.reginfo.gov/public/do/eAgendaViewRule?RIN=1615-AC85&pubId=202504" },
      { label: "Federal Register — Unified Agenda", href: "https://www.federalregister.gov/documents/2025/09/22/2025-18329/unified-agenda-of-federal-regulatory-and-deregulatory-actions" },
    ],
    sections: [
      { title: "The stated objective", paragraphs: ["DHS refers to codifying current guidance, updating the extraordinary-ability provisions and clarifying evidential requirements for first-preference and National Interest Waiver petitions."] },
      { title: "Current status of the project", paragraphs: ["A Unified Agenda entry is not a published proposed rule. Without final wording and a commencement date, it is not possible to say reliably which evidence will become stronger or weaker."] },
      { title: "Prepare or wait", paragraphs: ["We do not stop a ready project solely because a rule has no final text or effective date. A sounder approach is to support each material proposition separately and conduct a fresh check after official publication."] },
    ],
  },
  {
    slug: "france-carte-talent-renaming",
    tag: "France · Carte talent",
    title: "Carte talent: what changed after Passeport Talent",
    description: "The current official name of the French talent routes and why the former term still appears.",
    reading: "4 min read",
    published: "2025-06-16",
    author: "Nikita Samotsvetov",
    lead: "Decree no. 2025-539 replaced passeport talent with carte talent in the legislation and reorganised some subcategories. The changes took effect on 16 June 2025, although some official and reference pages still use the former term.",
    relatedCountry: "france",
    sources: [
      { label: "Légifrance — Decree no. 2025-539", href: "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000051736256" },
      { label: "France-Visas — International talents", href: "https://france-visas.gouv.fr/en/talents-internationaux-et-attractivite-economique" },
    ],
    sections: [
      { title: "The official name", paragraphs: ["The code now uses carte talent. Our material therefore uses the current term and, where useful, gives the former search term Passeport Talent alongside it so that readers can recognise the same developing system."] },
      { title: "The source of the terminology conflict", paragraphs: ["The former name remains in search results, everyday usage and some government pages. Without the date of a source, it can be difficult to tell whether it describes the structure before or after June 2025."] },
      { title: "Items to verify", paragraphs: ["Check the overall Talent family, the exact current subcategory, the conditions applying to the project or employment and the relevant CESEDA provision. An old bundle should not be carried into the new structure automatically."] },
    ],
  },
  {
    slug: "france-civic-exam-2026",
    tag: "France · Integration requirements",
    title: "France's civic examination from 2026: 40 questions and an 80% pass mark",
    description: "Who needs the new examen civique and why the precise card-issue procedure matters for Carte talent.",
    reading: "5 min read",
    published: "2025-12-19",
    author: "Nikita Samotsvetov",
    lead: "From 1 January 2026, the examen civique applies to naturalisation and the first issue of certain multi-year or resident cards. The examination has 40 questions and requires 32 correct answers.",
    relatedCountry: "france",
    sources: [
      { label: "Service-Public — the new examen civique", href: "https://www.service-public.fr/particuliers/actualites/A18713" },
      { label: "Légifrance — Order of 10 October 2025", href: "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000052381620" },
      { label: "Légifrance — CIR exemptions, Article L413-5", href: "https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006070158/LEGISCTA000042771476/" },
    ],
    sections: [
      { title: "Format", paragraphs: ["The digital test lasts up to 45 minutes and covers the principles of the Republic, institutions, rights and duties, history, culture and everyday situations. The pass mark is 80%."] },
      { title: "The exact procedure determines whether the exam applies", paragraphs: ["Many Carte talent holders are exempt from the contrat d'intégration républicaine, and Talent is often issued directly as a multi-year card under a separate procedure. The obligation nevertheless depends on the precise card, whether the application is a first grant or renewal, and the next status sought."] },
      { title: "Our review", paragraphs: ["We record the exact name of the current permission and the proposed next application, then compare it with the operative procedure. The general word Talent is insufficient to establish an exemption."] },
    ],
  },
  {
    slug: "france-naturalisation-b2",
    tag: "France · Citizenship",
    title: "Naturalisation in France now requires spoken and written B2",
    description: "The B2 requirement from 1 January 2026, accepted evidence and the civic examination.",
    reading: "4 min read",
    published: "2026-01-02",
    author: "Nikita Samotsvetov",
    lead: "From 1 January 2026, naturalisation by decree requires French at B2 or above in both speaking and writing. A separate civic examination also applies.",
    relatedCountry: "france",
    sources: [
      { label: "Service-Public — evidence of French level", href: "https://www.service-public.fr/particuliers/vosdroits/F11926" },
      { label: "Service-Public — civic examination for naturalisation", href: "https://www.service-public.fr/particuliers/vosdroits/F39426" },
    ],
    sections: [
      { title: "What B2 includes", paragraphs: ["The level requires comprehension of complex text and the ability to develop an argument clearly. Comfortable conversation in everyday settings does not establish the written B2 component."] },
      { title: "Accepted evidence", paragraphs: ["Service-Public lists accepted French diplomas and certificates, together with TCF or TEF results issued less than two years earlier. Special rules apply in certain medical circumstances and for some older refugees."] },
      { title: "When to begin", paragraphs: ["Where work and daily life remain in English, French will not necessarily develop to B2 without a plan. We recommend checking the actual level early and keeping the language-learning timetable separate from the residence-renewal calendar."] },
    ],
  },
  {
    slug: "portugal-nationality-2026",
    tag: "Context · Portugal",
    title: "Portugal changed the residence period for naturalisation: the 2026 law",
    description: "Seven years for EU and Portuguese-speaking-country nationals, ten years for others, and the transitional provision.",
    reading: "5 min read",
    published: "2026-05-19",
    author: "Nikita Samotsvetov",
    lead: "Organic Law no. 1/2026 was published on 18 May and took effect on 19 May 2026. It requires seven years of lawful residence for EU nationals and nationals of countries where Portuguese is an official language, and ten years for other nationals.",
    relatedCountry: "uk",
    sources: [
      { label: "Diário da República — Organic Law no. 1/2026", href: "https://diariodarepublica.pt/dr/detalhe/lei-organica/1-2026-1123539996" },
      { label: "Diário da República — consolidated Nationality Law", href: "https://diariodarepublica.pt/dr/legislacao-consolidada/lei/1981-34536975" },
    ],
    sections: [
      { title: "The date of the law matters", paragraphs: ["The measure was promulgated on 3 May, published on 18 May and entered into force the following day. For the operative law, the publication and commencement dates matter; the signature date alone is insufficient."] },
      { title: "Transitional provision", paragraphs: ["Administrative procedures already under way on 19 May 2026 remain subject to the previous version of the law. Two applicants with similar residence histories may therefore fall under different regimes depending on when the procedure began."] },
      { title: "Why Portugal appears in our analysis", paragraphs: ["This development helps compare long-term relocation horizons. We do not handle Portuguese matters, so a decision on a specific procedure should be checked with a professional practising Portuguese law."] },
    ],
  },
  {
    slug: "europe-routes-2026-context",
    tag: "Context · Europe in 2026",
    title: "European status pathways are changing in four different ways",
    description: "What has taken effect in Portugal, France and Spain, and what remains a proposal in the United Kingdom.",
    reading: "6 min read",
    published: "2026-08-12",
    author: "Nikita Samotsvetov",
    lead: "The 2026 changes have different legal statuses: some are already in force, some take effect later, and the UK's ten-year model remains a proposal.",
    relatedCountry: "uk",
    sources: [
      { label: "GOV.UK — Earned Settlement consultation", href: "https://www.gov.uk/government/consultations/earned-settlement/a-fairer-pathway-to-settlement-statement-and-accompanying-consultation-on-earned-settlement-accessible" },
      { label: "Diário da República — Nationality Law", href: "https://diariodarepublica.pt/dr/detalhe/lei-organica/1-2026-1123539996" },
      { label: "Service-Public — examen civique", href: "https://www.service-public.fr/particuliers/actualites/A18713" },
      { label: "BOE — 2026 SMI", href: "https://www.boe.es/buscar/act.php?id=BOE-A-2026-3815" },
    ],
    sections: [
      { title: "Four different legal positions", paragraphs: ["Portugal changed the residence periods for naturalisation. France introduced B2 and a civic examination for the relevant procedures. Spain raised the financial threshold in line with the SMI. The United Kingdom set B2 for settlement from March 2027. The ten-year Earned Settlement model was presented as a consultation proposal and was not contained in the operative rules."] },
      { title: "A trend with route-specific effects", paragraphs: ["States are asking for more evidence of durability through language, income, genuine activity and integration. The effect on a talent route depends on its own rules."] },
      { title: "How this affects route selection", paragraphs: ["We compare the entire horizon: entry, extension, settlement, citizenship, dependence on an employer and the position of family members. The shortest visa does not necessarily create the most stable route."] },
    ],
  },
];
